### PR TITLE
Implement error handling for the useFeeEstimation hook

### LINKED ISSUE #1382: Implement error handling for the `useFeeEstimation` hook to ensure the application can gracefully handle errors in fee estimation.
Implement error handling for the `useFeeEstimation` hook to ensure the application can gracefully handle errors in fee estimation.

```diff
-  const { estimateFee } = useFeeEstimation(fromChain ?? '');
+  const { estimateFee, error: feeEstimationError } = useFeeEstimation(fromChain ?? '');
+  if (feeEstimationError) {
+    console.error("Error estimating fee:", feeEstimationError);
+    return;
+  }
```

---

<details>
<summary>Committable suggestion</summary>

> :bangbang: **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation.

```suggestion
```

</details>

_Originally posted by @coderabbitai[bot] in https://github.com/quicksilver-zone/quicksilver/pull/1374#discussion_r1548394776_

### PR DESCRIPTION
**Pull request by tiendn**
## 1. Summary
Implement error handling for the `useFeeEstimation` hook to ensure the application can gracefully handle errors in fee estimation.
**Example:**
```diff
-  const { estimateFee } = useFeeEstimation(fromChain ?? '');
+  const { estimateFee, error: feeEstimationError } = useFeeEstimation(fromChain ?? '');
+  if (feeEstimationError) {
+    console.error("Error estimating fee:", feeEstimationError);
+    return;
+  }
```
Closes #1382

## 2.Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 3. Implementation details

Add `error` state value on `useFeeEstimation` hook

## 4. How to test/use
use `error` props from `useFeeEstimation`, if `error` existed, please check it or show to user

## 5. Checklist

- [x] Does the Readme need to be updated? No

### CODE REVIEW

**Review by tropicaldog — CHANGES_REQUESTED** [review]
Please remove `yarn.lock` sir

**Comment by tiendn** [comment]
I've deleted. Tks @tropicaldog !

**Comment by faddat** [comment]
Can you please make the text on this PR more descriptive?  

It should say what it is doing, instead of just noting that it fixes issue 1382

**Comment by tiendn** [comment]
tks @faddat. I've updated

**Comment by faddat** [comment]
yep let's do this thing

**Comment by tiendn** [comment]
I regret to say that despite your words, actions were not taken. This affects your own credibility, not anyone else’s. I hope you can respond soon. Thank you.

**Comment by joe-bowman** [comment]
Excuse me?

**Comment by tiendn** [comment]
Hi @joe-bowman , can I get rewarded from contributor with PR merged as [this tweet](https://x.com/quicksilverzone/status/1787477012053213218?s=46) describe
https://x.com/quicksilverzone/status/1787477012053213218?s=46

**Comment by joe-bowman** [comment]
Absolutely. As we have previously advertised, the payments will be made on a monthly schedule. Now May has ended, the payments for that period will be made this week.

**Comment by tiendn** [comment]
Thank you. Could you please let me know how the payment should be made?

**Comment by tiendn** [comment]
Hi Joe, today is Friday. Do you have any update?

My address: osmo1k62zl5tuhhhmazresfvyttev4k5866pss04xzs

**Comment by tiendn** [comment]
It seems like you are a promise-breaker @joe-bowman . 
Sad!

**Comment by tiendn** [comment]
Hey @joe-bowman @tropicaldog @faddat any updates?

**Pull request merged**
