### PR TITLE
feat!: bump cosmos-sdk to v0.47.x

### PR DESCRIPTION
**Pull request by tuantran1702**
## 1. Summary
Fixes # (issue)

## 2.Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 5. Checklist

- [ ] Does the Readme need to be updated?

### Release Notes

- **New Features**
	- Updated the application to utilize CometBFT libraries, enhancing performance and compatibility.
	- Introduced new functionalities for managing tokenized shares, including rewards and transactional operations.
	- Added a `RegisterNodeService` method to enhance gRPC capabilities.
  
- **Bug Fixes**
	- Addressed issues related to outdated dependencies, ensuring better stability and security.

- **Documentation**
	- Standardized naming conventions in API documentation for clarity.

- **Chores**
	- Updated dependency versions in `go.mod` to ensure compatibility with the latest libraries.
	- Refactored import statements across various files to reflect the transition to CometBFT.

### CODE REVIEW

**Comment by faddat** [comment]
this is looking good so far, thank you

**Comment by faddat** [comment]
* #1154

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>f05d194</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/Ci4MUUaKa7w2EUmaMNzoHW1145BB'>https://vercel.com/quicksilver/quicksilver/Ci4MUUaKa7w2EUmaMNzoHW1145BB</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8502391434)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>cc0026a</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/GbcqQLZzUG2HbEvUhU9NEvjewZhU'>https://vercel.com/quicksilver/quicksilver/GbcqQLZzUG2HbEvUhU9NEvjewZhU</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8505372781)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>c65da07</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/7ANTkKCBCv7QFehmu94tpkS7uqHG'>https://vercel.com/quicksilver/quicksilver/7ANTkKCBCv7QFehmu94tpkS7uqHG</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8537625209)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>33bf885</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/EuzJATMXvjRXSRDebTnFV36PZQz2'>https://vercel.com/quicksilver/quicksilver/EuzJATMXvjRXSRDebTnFV36PZQz2</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8537630816)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>62b3200</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/D7NFBpbW93eMz5MYdJefXXLx4PgT'>https://vercel.com/quicksilver/quicksilver/D7NFBpbW93eMz5MYdJefXXLx4PgT</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8537875152)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>4d601ac</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/8H7HPMrzJGQzN4ZCsCwFGsTGeUxb'>https://vercel.com/quicksilver/quicksilver/8H7HPMrzJGQzN4ZCsCwFGsTGeUxb</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8552198010)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>ff27ba0</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/kDSy1bUW2kDFCkCz15KhnczdJ6VP'>https://vercel.com/quicksilver/quicksilver/kDSy1bUW2kDFCkCz15KhnczdJ6VP</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8564056845)

**Comment by faddat** [comment]
I made #1413 to resolve conflicts here.  My first pass basically tells me that we've got too many tests disabled right now.

If we have commented out a test:

* it is no longer relevant and should be removed

OR

* it needs fixing


-----------


@tropicaldog please try to keep main merged into this as frequently as possible.  Small merges are a lot easier than big ones.  

I think it is increaasingly important to get this change in, so that we can benefit from ecosystem-wide improvements, and enable permissionless cosmwasm.

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>7476aad</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/HJzU9TyCeB6ZqtKzvhMRLGHf2Jiq'>https://vercel.com/quicksilver/quicksilver/HJzU9TyCeB6ZqtKzvhMRLGHf2Jiq</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8656442117)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>b0feb60</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/3w5gSCcGS59Taomnsic61CGJ2qsW'>https://vercel.com/quicksilver/quicksilver/3w5gSCcGS59Taomnsic61CGJ2qsW</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8656449757)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>fab3e9a</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/8botqTBhjCw3w1r2uRQ1X3yEnM6g'>https://vercel.com/quicksilver/quicksilver/8botqTBhjCw3w1r2uRQ1X3yEnM6g</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8656626568)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>5ef9577</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/3kTH8iLyCmHtTzuHNNRSFm8SKiiv'>https://vercel.com/quicksilver/quicksilver/3kTH8iLyCmHtTzuHNNRSFm8SKiiv</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8656665368)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>f08683a</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/ASt4ok2RtKiHdnyUG4WynTjewBsQ'>https://vercel.com/quicksilver/quicksilver/ASt4ok2RtKiHdnyUG4WynTjewBsQ</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8706994583)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>fcaa066</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/4G7uhCdzt7dhjuUPLwk9fdJJEvWZ'>https://vercel.com/quicksilver/quicksilver/4G7uhCdzt7dhjuUPLwk9fdJJEvWZ</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8719595830)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>0ffa080</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/3QF9E383GrMGQTRtcSSksu2UmimR'>https://vercel.com/quicksilver/quicksilver/3QF9E383GrMGQTRtcSSksu2UmimR</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8869255695)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>50b904f</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1202.app-dev.quicksilver.zone'>https://pr-1202.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/6ubSR4sHtPCbyNsPv3d5QZoYy3yH'>https://vercel.com/quicksilver/quicksilver/6ubSR4sHtPCbyNsPv3d5QZoYy3yH</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8869312625)

**Comment by faddat** [comment]
@tropicaldog could you please:

* get this ready to merge
  * fix conflicts
  * find any place where we've reduced test coverage and shouldn't have

I think we're just about ready for this one.  Thanks for your help and patience here.

**Comment by tropicaldog** [comment]
> @tropicaldog could you please:
> 
> * get this ready to merge
>   
>   * fix conflicts
>   * find any place where we've reduced test coverage and shouldn't have
> 
> I think we're just about ready for this one. Thanks for your help and patience here.

Yes sir @faddat , should get this up for testing in devnet so that we could catch any issues

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Pull request closed without merging**
