### PR TITLE
Test for GovReopenChannel

### PR DESCRIPTION
**Pull request by DongLieu**
## 1. Summary
Fixes #617

## 2.Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 5. Checklist

- [ ] Does the Readme need to be updated?

### CODE REVIEW

**Comment by joe-bowman** [comment]
This test only checks that there was not an error. What is the function doing? How can we assert this?

**Comment by DongLieu** [comment]
For example, the port connection has been set correctly

**Comment by joe-bowman** [comment]
@DongLieu - looks good - can you resolve the conflicts please?

**Comment by DongLieu** [comment]
Ok, thank joe-bowman

**Review by ThanhNhann — APPROVED** [review]

**Pull request merged**
