### PR TITLE
remove assets page

### PR DESCRIPTION
**Pull request by faddat**
This PR removes the assets page from the quicksilver webui, enabling it to build, and enabling us to test its deployment to github pages.

### CODE REVIEW

**Comment by faddat** [comment]
hmmmm will unfix my "fix"

**Comment by faddat** [comment]
@chalabi2 - after you review and merge this, it should be published to github pages.  If it doesn't, lmk 🖖

**Comment by faddat** [comment]
I'll also make an issue so that CI for the chain doesn't slow down web dev...

**Review by chalabi2 — APPROVED** [review]
Removes assets page with no breaking changes

**Review by chalabi2 — APPROVED** [review]

**Comment by chalabi2** [comment]
> I'll also make an issue so that CI for the chain doesn't slow down web dev...

So long as the web-ui directory never depends on chain or js(npm packages only) stuff we should be okay.

**Comment by faddat** [comment]
@chalabi2 the chain CI can take a long time to run, so I'm going to roll with it.  Need to get your approvals a little more power, but I think we are moving good :)!

**Pull request merged**
