### PR TITLE
fix: issue 1381 using startWiths instead of substring for check stringg prefixess

### LINKED ISSUE #1381: Consider using `startsWith` for a cleaner and more efficient way to check string prefixes.
Consider using `startsWith` for a cleaner and more efficient way to check string prefixes.

```diff
- if (denom.substring(0, 1) == "Q" || denom.substring(0, 2) == "AQ"){
+ if (denom.startsWith("Q") || denom.startsWith("AQ")){
```

---

<details>
<summary>Committable suggestion</summary>

> :bangbang: **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation.

```suggestion
    if (denom.startsWith("Q") || denom.startsWith("AQ")){
```

</details>

_Originally posted by @coderabbitai[bot] in https://github.com/quicksilver-zone/quicksilver/pull/1374#discussion_r1548394750_

### PR DESCRIPTION
**Pull request by tiendn**
## 1. Summary
`startWiths` look more clear than use `subString`, and have better performance.
Fixes #1381

string comparative performance

## 2.Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 3. Implementation details
use `startWiths` function

## 5. Checklist

- [ ] Does the Readme need to be updated?

### CODE REVIEW

**Review by tropicaldog — APPROVED** [review]

**Review by tropicaldog — APPROVED** [review]
small but nice improvement, thanks @tiendn

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Comment by tiendn** [comment]
Hey @faddat . Can u check this PR?

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Comment by tiendn** [comment]
OK bye @joe-bowman

**Pull request closed without merging**
