### PR TITLE
refactor(icq-relayer): reverse conditional pkg/runner.flush for more idiomatic Go

### PR DESCRIPTION
**Pull request by odeke-em**
By inverting nesting conditions, the code was made much clearer and more idiomatic Go.

## Summary by CodeRabbit

- **Bug Fixes**
    - Improved error handling for message sending, ensuring clearer processing of failed attempts.
  
- **Refactor**
    - Simplified control flow in message handling, reducing complexity and enhancing readability.
    - Eliminated unnecessary logging for empty message sends, streamlining the process.
    - Streamlined deduplication of messages for efficiency.

### CODE REVIEW

**Comment by faddat** [comment]
I love these here inversions.  I am just gonna work though the tests.

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Pull request closed without merging**
