### PR TITLE
refactor: add icq relayer to the quicksilver repository

### PR DESCRIPTION
**Pull request by faddat**
## 1. Summary
Add the icq relayer to the qucksilver repository

## 2.Type of change

Monorepo refactor

## 3. Implementation details

Just moved the code in here from elsewhere. 

## 4. How to test/use

cd icq-relayer
go test ./...

### CODE REVIEW

**Comment by joe-bowman** [comment]
Ser, we need the icq-relayer tagged v0.9.1 which is the latest, rather than main.

**Comment by faddat** [comment]
Gotcha.  I'll do that.

**Review by joe-bowman — CHANGES_REQUESTED** [review]
wrong repo ;)

**Comment by joe-bowman** [comment]
https://github.com/ingenuity-build/interchain-queries/tree/v0.9.1

**Pull request closed without merging**
