### PR TITLE
update: refocus all breakpoints

### PR DESCRIPTION
**Pull request by chalabi2**
## 1. Summary
Fixes # (issue)
This PR fixes most breakpoints 

Devices tested
- Iphone 14 pro max - SE
- Galaxy S8+ - S20 Ultra
- Galaxy fold
- Ipad Air - Mini - Pro
- Surface Pro Edge
- Macbooks
- Ultrawide
## 2.Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by chalabi2** [comment]
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> Name 	Status 	Preview 	Comments 	Updated (UTC)
> **quicksilver** 	🔄 Building ([Inspect](https://vercel.com/quicksilver/quicksilver/AV6vkQEWNUuv3VgQ1fGubM4Fe5bq)) 	[Visit Preview](https://vercel.live/open-feedback/quicksilver-git-web-ui-breakpoints-quicksilver.vercel.app?via=pr-comment-visit-preview-link&passThrough=1) 	💬 [**Add feedback**](https://vercel.live/open-feedback/quicksilver-git-web-ui-breakpoints-quicksilver.vercel.app?via=pr-comment-feedback-link) 	May 14, 2024 11:35pm

@joe-bowman Please review these breakpoint changes as ive changed the way im displaying the quicksilver written logo

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>0e9fb10</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1608.app-dev.quicksilver.zone'>https://pr-1608.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/TxVMbXZ23R86XaBQYMmRbBLKb5nr'>https://vercel.com/quicksilver/quicksilver/TxVMbXZ23R86XaBQYMmRbBLKb5nr</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/9087602682)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>417d571</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1608.app-dev.quicksilver.zone'>https://pr-1608.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/GF4TtaWeWd6Yasn71Z4PfpyTq4vb'>https://vercel.com/quicksilver/quicksilver/GF4TtaWeWd6Yasn71Z4PfpyTq4vb</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/9087753261)

**Review by joe-bowman — COMMENTED** [review]
lgtm

**Comment by chalabi2** [comment]
> lgtm

@joe-bowman took it out of review

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>6965f52</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1608.app-dev.quicksilver.zone'>https://pr-1608.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/4K5pLPSnq6SryHz7ieEMkP4EshAZ'>https://vercel.com/quicksilver/quicksilver/4K5pLPSnq6SryHz7ieEMkP4EshAZ</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/9150090758)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>1b5d879</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1608.app-dev.quicksilver.zone'>https://pr-1608.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/ALqS1CJQvQJtXcS4gYmk5EnovAfW'>https://vercel.com/quicksilver/quicksilver/ALqS1CJQvQJtXcS4gYmk5EnovAfW</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/9150122728)

**Review by joe-bowman — APPROVED** [review]

**Pull request merged**
