### PR TITLE
refactor: remove token factory

### LINKED ISSUE #1474: Remove tokenfactory
## Summary

In accordance with removal of old cosmwasm, lets pull tokenfactory too, and re-add the latest when we replace CW.

### PR DESCRIPTION
**Pull request by minhngoc274**
## 1. Summary
Close #1474 

## 2.Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 5. Checklist

- [ ] Does the Readme need to be updated?

## Summary by CodeRabbit

- **New Features**
  - Added `GetScopedICAControllerKeeper` to enhance interface implementation.
  - Introduced new upgrade handler for better version management.

- **Refactor**
  - Updated numerous modules to `ibc-go` version 6 for improved integration.
  - Removed all references and configurations related to `wasm` to streamline app functionalities.
  - Simplified initializations and settings across various modules for better performance and maintainability.

- **Bug Fixes**
  - Adjusted import paths and references to ensure compatibility with updated modules.

- **Chores**
  - Updated BUF_VERSION for enhanced Protobuf handling.
  - Removed outdated code and comments to maintain code cleanliness.

### CODE REVIEW

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>84714f6</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1490.app-dev.quicksilver.zone'>https://pr-1490.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/3P5vxccvea9Nq242Vge7bzmKRm47'>https://vercel.com/quicksilver/quicksilver/3P5vxccvea9Nq242Vge7bzmKRm47</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8820473471)

**Comment by minhngoc274** [comment]
we should merge this one #1421 first

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>bdfebce</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1490.app-dev.quicksilver.zone'>https://pr-1490.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/5MjjSP7ji8BZKq2R5sUZhqewtCdi'>https://vercel.com/quicksilver/quicksilver/5MjjSP7ji8BZKq2R5sUZhqewtCdi</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8826561403)

**Comment by joe-bowman** [comment]
Rebased on main post ibc-v6 merge, and fixed a couple of bugs.

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>bc313d9</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1490.app-dev.quicksilver.zone'>https://pr-1490.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/6KiBWw39GFeZbefkcAJ6yLPZejbt'>https://vercel.com/quicksilver/quicksilver/6KiBWw39GFeZbefkcAJ6yLPZejbt</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8836088824)

**Pull request merged**
