### PR TITLE
Use the nested if's linter to reduce complexity globally

### LINKED ISSUE #1609: Use the nested if's linter to reduce complexity globally
## Summary

Related to #1158 

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

### PR DESCRIPTION
**Pull request by pysel**
## 1. Summary
Fixes #1609

Enables gocyclo linter

### CODE REVIEW

**Review by tropicaldog — CHANGES_REQUESTED** [review]
Thanks @pysel for contributing! Could you fix the lint errors after adding the gocyclo lint? It seems there's quite lot of work to be done, would be very nice if we can actually reduce the complexity globally.

**Comment by pysel** [comment]
hey @tropicaldog . I added nolints to problematic places. I do not have much context on problematic functions, so I would probably not try to refactor them, since I might introduce unexpected bugs by doing that

CI should pass now though

**Comment by tropicaldog** [comment]
Yeah I guess this PR should be merged after the lint issue is fixed, wdyt @faddat @joe-bowman?

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Pull request closed without merging**
