### PR TITLE
Create ROADMAP.md

### PR DESCRIPTION
**Pull request by faddat**
## 1. Summary
Fixes # (issue)

## 2.Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 5. Checklist

- [ ] Does the Readme need to be updated?

## Summary by CodeRabbit

- **Documentation**
	- Introduced an official roadmap for the quicksilver project starting from version 1.5.0.

### CODE REVIEW

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>791fab0</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1264.app-dev.quicksilver.zone'>https://pr-1264.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/DQqhFKqx1qKpDyot9z29BaCviFrM'>https://vercel.com/quicksilver/quicksilver/DQqhFKqx1qKpDyot9z29BaCviFrM</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8643101714)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>3400924</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1264.app-dev.quicksilver.zone'>https://pr-1264.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/3VUaLnMBbNe4mRZBiz3Q1PWfHbFU'>https://vercel.com/quicksilver/quicksilver/3VUaLnMBbNe4mRZBiz3Q1PWfHbFU</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8643448919)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>a8cdc0e</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1264.app-dev.quicksilver.zone'>https://pr-1264.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/5WczmPuANQGf2BGR29xqA4oanmpf'>https://vercel.com/quicksilver/quicksilver/5WczmPuANQGf2BGR29xqA4oanmpf</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8643450641)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>3dfea5a</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1264.app-dev.quicksilver.zone'>https://pr-1264.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/BNQBxfBd1MucJ5G2TMwJGpbHdQWG'>https://vercel.com/quicksilver/quicksilver/BNQBxfBd1MucJ5G2TMwJGpbHdQWG</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8643451892)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>99c8900</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1264.app-dev.quicksilver.zone'>https://pr-1264.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/EDct4A4Z3a6XRV5bDRDqwrCsiUtn'>https://vercel.com/quicksilver/quicksilver/EDct4A4Z3a6XRV5bDRDqwrCsiUtn</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8774186135)

**Review by tropicaldog — APPROVED** [review]

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>8be8dbd</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1264.app-dev.quicksilver.zone'>https://pr-1264.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/BZWHzqijWG1XTGBKaPp34YjdYTYq'>https://vercel.com/quicksilver/quicksilver/BZWHzqijWG1XTGBKaPp34YjdYTYq</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8862458443)

**Comment by odeke-em** [comment]
@faddat a fleshed out roadmap as we spoke about 2 months ago will massively help out with new contributions too; kudos for starting this one.

**Comment by faddat** [comment]
Yep, we 100% need to add some detail to this.

**Pull request merged**
