### PR TITLE
x/participationrewards/keeper: fuzz CalcUserValidatorSelectionAllocations

### PR DESCRIPTION
**Pull request by odeke-em**
This change adds a fuzzer for CalcUserValidatorSelectionAllocations as it seems like a spot for which more panel beating is needed.

## Summary by CodeRabbit

- **Tests**
	- Introduced fuzz testing for allocation calculation logic in the participation rewards module.

### CODE REVIEW

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Comment by odeke-em** [comment]
Hey @joe-bowman, I tagged y'all twice though you marked this PR stale. Kindly help me take a look at it.

**Review by tropicaldog — APPROVED** [review]

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

**Pull request merged**
