### PR TITLE
Working UI Branch

### PR DESCRIPTION
**Pull request by chalabi2**
## 1. Summary
Working draft PR for webui 
## 2.Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 3. Implementation details
This is the new Quivksilver Web-UI

## 4. How to test/use
```
cd web-ui
bun install
bun run dev
```
## 6. Limitations (optional)
This is still a WIP. This branch may be broken at times and should not be merged without review

### CODE REVIEW

**Review by faddat — DISMISSED** [review]

**Comment by faddat** [comment]
@chalabi2 if it's cool with you, I would like to get this one merged and in general merge it more routinely, so that I can begin work on embedding the user interface into the go applications so that the user interface becomes fully uncensorable.

**Comment by chalabi2** [comment]
> @chalabi2 if it's cool with you, I would like to get this one merged and in general merge it more routinely, so that I can begin work on embedding the user interface into the go applications so that the user interface becomes fully uncensorable.

@faddat will this effect the development of the web app in any capacity? I assume there are constrains to integrating the front end with the go application?

**Comment by faddat** [comment]
@chalabi2 nope.  Basically we just need to merge this branch.  Then I will change the golang app so that:

1) before the golang app is compiled in ci, we build the web app
2) the output of the built web app is embedded in the chain's binary
3) the web app is served from the files embedded in the chains binary.

So, basically at this point the ask is like:

1) can we merge this branch?
2) can we merge branches like this one more frequently in the future so that we can get the web app (even more) integrated in the ci flow?

**Comment by chalabi2** [comment]
@faddat you should be good to merge this and add it, please keep in mind its still got some bugs and query errors, but we are getting there!

**Review by joe-bowman — APPROVED** [review]

**Pull request merged**
