### PR TITLE
Add UI working branch

### PR DESCRIPTION
**Pull request by chalabi2**
## 1. Summary
Add the bunDev working branch
## 2.Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 4. How to test/use

```
bun install
bun run dev
```

## 6. Limitations (optional)
Uncomplete

### CODE REVIEW

**Comment by chalabi2** [comment]
@faddat We need the change to the workflow file for testing the deployment in this commit (e67d18e)[https://github.com/quicksilver-zone/quicksilver/pull/917/commits/e67d18e0f0b41ab0ffde43cc8f47be16a886eaa2] merged.

**Comment by chalabi2** [comment]
Also, it probably wouldnt hurt to just merge this branch where every thing builds and works into main?

**Comment by faddat** [comment]
Yep that works sir, how about make a PR and let's merge it :D

**Review by faddat — APPROVED** [review]

**Comment by faddat** [comment]
@chalabi2 if you take this out of draft you should now be able to merge it :)

Seems the monorepo is working -- success in making smaller changesets :D

**Review by joe-bowman — APPROVED** [review]
mergy mergy

**Pull request merged**
