### PR TITLE
 !upgrade: Cosmos SDK to v0.50.x, ibc v8

### LINKED ISSUE #941: Zero features upgrade to sdk 50
We need to upgrade quicksilver to sdk 50, without making significant changes other than the sdk or adding/removing features.

This will allow us to more quicksilver closer to a pure infrastructure product, compatible with as many chains as possible, and non-intrusive. 

Boring is beautiful.

* #931 

The above PR is likely the upgrade branch.  Please feel free to make PR's to it.

### PR DESCRIPTION
**Pull request by tropicaldog**
#  Overview
Closes #941

This upgrade bumps the project's SDK to version v0.50.3, IBC to v8 but **does not supposed to introduce any changes to existing application functionality**. This document outlines the major areas of change and their impact.

# Current issues

- [x] Wasmbindings(in review)
- [x]  x/airdrop (In review)
- [x]  x/interchainstaking(In review)
- [ ]  icq-relayer
- [ ] tpsCounter
- [ ] utils folder(proofs.go)
- [ ] transferMiddleware change(from main branch)
- [ ] upgrade.go, upgrade_test.go(test failing for unknown reasons)
- [ ] **refactor remaining changes according to main branch to achieve parity(should do last to avoid confusion)**

# High-level Changes

Bump Cosmos SDK from v0.46.16 to v0.50.3
Bumping IBC from v5 to v8
Refactor modules to match new SDK syntax
Update both quicksilver and third-party proto-file to use newer libraries.
Migrate deprecated methods from older SDK to quicksilver

# Detailed Changes

### App folder
+ Basic Module Manager
+ Remove app.RegisterRoutes

+ Remove the need to passing encodingConfig to NewQuicksilver, just create both Codec and LegacyAmino inside the function body
```go
interfaceRegistry, err := types.NewInterfaceRegistryWithOptions(types.InterfaceRegistryOptions{
		ProtoFiles: proto.HybridResolver,
		SigningOptions: signing.Options{
			AddressCodec: address.Bech32Codec{
				Bech32Prefix: sdk.GetConfig().GetBech32AccountAddrPrefix(),
			},
			ValidatorAddressCodec: address.Bech32Codec{
				Bech32Prefix: sdk.GetConfig().GetBech32ValidatorAddrPrefix(),
			},
		},
	})
	if err != nil {
		panic(err)
	}
	appCodec := codec.NewProtoCodec(interfaceRegistry)
	cdc := codec.NewLegacyAmino()
	txConfig := authtx.NewTxConfig(appCodec, authtx.DefaultSignModes)
	
```

+ Refactor BeginBlocker and EndBlocker function signature, now they are just accepting one single context argument 
```diff
- BeginBlock(sdk.Context, abci.RequestBeginBlock)
+ BeginBlock(context.Context) error
```

```diff
- EndBlock(sdk.Context, abci.RequestEndBlock) []abci.ValidatorUpdate
+ EndBlock(context.Context) error
```

+ Removal of DeliverTx in BaseApp interface https://github.com/cosmos/cosmos-sdk/blob/release/v0.50.x/UPGRADING.md#baseapp
	> BaseApp calls of `BeginBlock` & `Endblock` are now private but are still exposed to the application to define via the `Manager` type. `FinalizeBlock` is public and should be used in order to test and run operations. This means that although `BeginBlock` & `Endblock` no longer exist in the ABCI interface, they are automatically called by `BaseApp` during `FinalizeBlock`. Specifically, the order of operations is `BeginBlock` -> `DeliverTx` (for all txs) -> `EndBlock`.
They do deliverTx privately, during the finalizeBlock method of ABCI. https://github.com/cosmos/cosmos-sdk/blob/7685abb8857773c147b7ba49496e8b9b06d13c0d/baseapp/abci.go#L713-L862. Not sure how we can add custom logic to the deliverTx phase now, to support logic of tpsCounter
+ Add custom logic for FinalizeBlock, to migrate the store correctly https://github.com/quicksilver-zone/quicksilver/blob/0bec6c1c520a1014047c48c65508f28301676378/app/app.go#L532-L551
+ Refactor MakeEncodingConfig. Now generated by creating a tempApp, then construct an encodingConfig from it.  [app/encoding.go](https://github.com/quicksilver-zone/quicksilver/pull/1060/files#diff-5b0b558d0a19d57e79af24fcfd5b1b099ced2eb2fe4447402069c892813478e9 "app/encoding.go")
### Cmd folder
Refactor based on the change on App folder, see detail on the https://github.com/quicksilver-zone/quicksilver/pull/1060/files#diff-b648a0ba5f73d63678f411584d6e97f8413a398ea4e50232311650b7f6b53ba1
### Wasmbinding folder
Use **NewMsgSubmitProposal** to submit the MsgStoreCode https://github.com/quicksilver-zone/quicksilver/blob/5393bbaa47356c19282c3df542f157debdaae3a5/wasmbinding/test/custom_query_test.go#L116-L129
#### Quicksilver protos
+ Change Int and Dec belong to old cosmos-sdk/types to cosmossdk/math by modifying the buf.yaml: https://github.com/quicksilver-zone/quicksilver/pull/1060/files#diff-456c026faff792a6ca7bd293f2453164c317ac23712c908b8526eef74e95c4d2
+ Regenerated new protobuf files
#### Thirdparty protos
Overall, the changes are:
	+ Gas datatype: from cosmos-sdktypes.Gas to plain uint64, since SDK50 removed Gas types
	+ cosmos-sdktypes Dec and Int are replaced with cosmossdk.io/math LegacyDec and Int
	+ fileDescriptor value are changed

Third party protos file(\*.pb.go) are updated, generated by cloning the original changes, change their proto to use newer cosmos sdk math and gogoproto libraries to their protos, then generate pb.go files using protocgen.sh scripts. Finally, move the newly generated proto files to Quicksilver repos, and make some required changes.

# Utility files

Migrated deprecated SDK46 banktypes method to quicksilver "bankutils" packages
[utils/bankutils/bank.go](https://github.com/quicksilver-zone/quicksilver/pull/1060/files#diff-875bb3bc2ae14f0e3dd411642bfc2b9c9627bcaa150f531ea377a1567b3da12a "utils/bankutils/bank.go"), not sure if it is correct way to handle the deprecated stuffs, I just want to keep the old functionality.

# Modules changes
### Overview
The *Module changes* section is for describing the changes in each module
Since we update the SDK version to v0.50, all modules need to follow the change accordingly. So, most of the changes are just replace types.math-> cosmossdk.io/Math, Dec->LegacyDec, cosmos-sdk/stores->seperate stores packages. These changes are pretty trivial, so it won't be discussed in detailed
### x/airdrop
Current status: In progress, some tests has not beed fixed/logic not refactored

No notable changes
### x/claimsmanager
Current status: In Review
Similar to x/airdrop changes, but no existing bugs remain.
### x/interchainquery
Current status: In Review
No notable changes, similar changes to x/airdrop
#### client folder
Current status: In review
No notable changes
#### keeper folder
Current status: In review
a major change is introduced. I bring the x/auth txBuilder to the quicksilver repo, in order to construct a valid sdk.Tx from msgs. https://github.com/quicksilver-zone/quicksilver/pull/1060/files#diff-c0cf771f814c0fd6ba394ed186f92fd959d422f61279ec57aba38cc8ef83372b

since sdk.TxDecoder now return sdk.Tx, so isn't able to return tx.Tx anymore
https://github.com/cosmos/cosmos-sdk/blob/7685abb8857773c147b7ba49496e8b9b06d13c0d/x/auth/tx/decoder.go

I constructed the Tx using the new TxBuilder, and the tests seems to work nicely with the tests: https://github.com/quicksilver-zone/quicksilver/blob/tuan/upgrade-sdk-v0.50.x/x/interchainstaking/keeper/receipt_test.go#L146-L155

### x/lsmtypes
Status: In review, test passed
No significant changes.
Detail changes: https://github.com/quicksilver-zone/quicksilver/pull/1060/files#diff-ace71f7aadb021f0ed0cabb67986e08b4ba90919b1733d397534760efbb67052

### x/mint
Status: In review, test passed
No significant changes
https://github.com/quicksilver-zone/quicksilver/pull/1060/files#diff-97ab51578583f8ac4f726ae9ea3c6f6496483d85b488a0b37546accc310a87aa

### x/participantsreward
Status: In review, test passed
using bankutils as replacement of SDK46 banktypes methods

Overall, still just changes similar to above modules.

### x/supply
Status: In review, test passed
No significant changes

### x/tokenfactory
Status: In review, test passed
No significant changes

# Current issues
#### Wasmbindings
~~Currently, I am not able to fix some of the tests due to newer wasmtypes~~
Update(24 Jan): fixed in 5393bbaa47356c19282c3df542f157debdaae3a5
Updated changes in the **Detailed Changes** section

#### Utilities Files
utils/proofs.go
 ``` go
 
	// TODO: ibc v8 remove the GetRoot method of ConsensusState, so can not 	
path := commitmenttypes.NewMerklePath([]string{module, url.PathEscape(string(key))}...)

```

This line doesn't work anymore, and I haven't figured an alternative method to this

#### x/airdrop

x/airdrop/claim_handler.go

Currently the way we iterate through proposals:
```go
k.govKeeper.IterateProposals(ctx, func(proposal govv1.Proposal) (stop bool) {
		_, found := k.govKeeper.GetVote(ctx, proposal.Id, addr)
		if found {
			voted = true
			return true
		}
		return false
	})
```
~~In SDK 50 they don't support the IterateProposals anymore, [docs](https://docs.cosmos.network/main/build/architecture/adr-062-collections-state-layer)~~

~~They said that the state of gov modules is now managed by the Collection API, but I haven't figured a way to access the collections. https://github.com/cosmos/cosmos-sdk/pull/16171~~

~~In the gov tests of Cosmos SDK, they access the Proposal field of govKeeper directly, but not sure how we could achieve the same thing, [proposal_test.go](https://github.com/cosmos/cosmos-sdk/blob/v0.50.3/x/gov/keeper/proposal_test.go)~~

Update(24 Jan): Fixed in e0b669b39c4ae56880b5eed06c76ea0f0d16f8e1, need review @joe-bowman @faddat 

#### x/interchainstaking

 + Not sure why the testchain generated using setupTestZone always has the "-1" at the end, so I need to modify some tests. for example "testchain2" -> "testchain2-1", not sure if it is my fault or some changes in the IBC library

+ x/interchainstaking/zones_test.go
	Now, when the types.Zone is initialize like this
``` go
zone = types.Zone{
		ConnectionId: "conn-test",
		ChainId:      chainID,
		LocalDenom:   "uqck",
		BaseDenom:    "qck",

	}
```
then the RedemptionRate, the LastRedemptionRate and the Tvl value, which is all sdkmath.LegacyDec types, is stored as \*big.Int(nil). But when it is stored and retrieved from the store, it is store in a different way.
```diff
Tvl: (math.LegacyDec) {
- i: (*big.Int)(<nil>)

+ i: (*big.Int)({
+ neg: (bool) false,
+ abs: (big.nat) <nil>

+ })
},
```

I resolve this by initialize it in the test
```go
	zone = types.Zone{
		ConnectionId: "conn-test",
		ChainId:      chainID,
		LocalDenom:   "uqck",
		BaseDenom:    "qck",
		// TODO: Not sure if should initialized here or not.
		RedemptionRate:     sdkmath.LegacyNewDec(0),
		LastRedemptionRate: sdkmath.LegacyNewDec(0),
		Tvl:                sdkmath.LegacyNewDec(0),
	}
```
but not sure if this issue would cause any problem in production

#### icq-relayer

After bumping ibc-go to v8, a problem arise, that the MsgUpdateClient doesn't have Header anymore, and also the `PackHeader` and `UnpackHeader` method also been removed from the `clienttypes` package. Haven't figured out a way to fix it yet
https://github.com/quicksilver-zone/quicksilver/blob/main/icq-relayer/pkg/runner/run.go#L639-L649

# Final thoughts

Most of the bugs I encountered during fixing the code is because the required module isn't properly registered, under new Cosmos SDK. The tests are very helpful to catch these kind of bugs, and also comparing the app initialization code from both https://github.com/CosmWasm/wasmd/blob/main/app/app.go and https://github.com/cosmos/ibc-go/blob/v8.0.0/testing/simapp/app.go prove to be very helpful for my upgrade process

### CODE REVIEW

**Comment by faddat** [comment]
@tropicaldog -- let's see what we can do to get this building.  Also I want to request that you try to resolve the "directly using bech32" issues -- check out how it is done in the sdk50 branch of wasmd.

**Comment by faddat** [comment]
@tropicaldog so another thing -- I had a very hard time with doing the relayer code and the quciksilver code separately.  

I posted this issue today:

* #1065

BUT!

If you think they should be done together, that is fine with me.  What I was thinking of doing is taking the relayer from this branch like:

```bash
git checkout origin/tuan/upgrade-sdk-v0.50.x -- icq-relayer
```

then 

* removing the replace for wasmd found in the icq-relayer folder
* find and replace github.com/ingenuity-labs/quicksilver in the icq-relayer folder

*  referencing this branch in go.mod like:

```bash
cd icq-relayer
go get github.com/quicksilver-zone/quicksilver@3f9226f
```

**but question**

what do you think?  Worth trying?

(Basically the question is about the size of the PR overall.  I do not know the correct answer offhand, so I am wondering what is your opinion :) ) .

**Comment by faddat** [comment]
It worked!

Size-reducing PR incoming :)

**Comment by tropicaldog** [comment]
@faddat yeah, it seems that the icq-relayer code is not that coupled to quicksilver source code, so seperating is perfecly okay I think

**Comment by faddat** [comment]
Yeah, it seemed to work well.  You may want to check out the icq-relayer folder from my branch into yours, because I'd introduced a few bugs in paths.  Anyhow if this works in prod, then we'll begin to use it in prod.  Thanks for your feedback!

Is there anything else that I can help you with on this PR?

**Comment by tropicaldog** [comment]
@faddat thanks, I will let you know asap if any problem arises with my work on this PR

**Comment by faddat** [comment]
Sir I'm seeing the opposite of problems :)

It looks great!

**Comment by faddat** [comment]
@tropicaldog -- I think that this PR is now ready for @joe-bowman to review.  I also think that you documented this PR very well.

Some of the items mentioned (like proofs.go) I am not sure that I am the best person to comment on.

**Comment by faddat** [comment]
@tropicaldog do you think that the refactors mentioned in section 4 are needed for the modules in question to work?  Have you tried, for example, doing a 100 block testnet using this code on your local machine?

**Comment by faddat** [comment]
well darn -- I realized that that might happen when I merged #1056 .  @tropicaldog -- @joe-bowman had a fixes PR today, which didn't auto-merge because coderabbit.ai had open conversations on it (apparently need to resolve coderabbit conversations too for automerge to work)

**Comment by faddat** [comment]
@tropicaldog are you OK with using this PR as a place to discuss the fine-grained details of the upgrade process?

It seems to me like all of the broad aspects, you have covered.  But I also think the items you mentioned in section 4 need addressing, as well as state migrations and an upgrade handler -- likely both.  

@joe-bowman what I usually recommend is to do it in "big" style like this, then merge but I noticed that the PR's merged today form a patch release.

**Comment by faddat** [comment]
@tropicaldog hey, I did the merge conflict, but I would feel more comfortable if you could review the changes in #1056 and resolve the conflict, and I think we should do a call/DM session with @joe-bowman -- overall I am very happy with this PR, and I'm going to fix the lint issues now.

It seems to me like you observe **great** practices programming.

Likely to take us another few days to one week to get merged to `main` especially since #1067 is not currently passing tests.

**Comment by faddat** [comment]
Screenshot 2024-01-21 at 5 16 01 PM

@tropicaldog if you configure the linter in your vscode / cursor, you get this "problems" bar.  Rn I'm doing some of the simple stuff, but I think there's some that we may need to collaborate on.  

:D

**Comment by faddat** [comment]
@tropicaldog I messed up your branch, I am reverting it to your last commit.  I'll create a PR into it.

**Comment by faddat** [comment]
@tropicaldog I'd say that your best next step is to merge the changes, because you and joe changed a few of the same files.

**Comment by tropicaldog** [comment]
> @tropicaldog I'd say that your best next step is to merge the changes, because you and joe changed a few of the same files.

Yes sir, I will do it tomorrow. Was busy finalizing some fixes,  I imagine the next steps would be something: 
- [ ] Merge main code
- [ ] Document changes
- [ ] List current issues
- [ ] Linting

**Comment by tropicaldog** [comment]
@faddat Yeah, my focus is on prioritizing the documentation of these changes asap.
I believe it could prove beneficial for our team to extend the upgrade to other chains to v50, and also I see this as an opportunity to enhance my understanding by thoroughly documenting the process, especially considering the somewhat instinct nature of the upgrade process. What are your thoughts on this?

**Comment by faddat** [comment]
hey @tropicaldog -- nice work here -- btw here's the v50 upgrade for lens, which is a dependency of quicksilver:

* https://github.com/notional-labs/lens

**Comment by tropicaldog** [comment]
@faddat  do you think it's good idea to postpone the upgrade and wait a little bit until the upstream code is more mature?

**Comment by faddat** [comment]
But yes but we should prepare the upgrade anyway. That will actually help us learn a bit more about the maturity of the code base.

So basically we can think about the next steps in segments. First of all we have to make it so that the chain runs from the binary that we produce, secondly we need to figure out tests. Thirdly, we need to write the upgrade handler. It's pretty important to us to get this upgrade finished relatively rapidly, and I believe that the problem with comet 38 is actually related to vote extensions. I have been working with the bera chain team about these issues.

So to answer your question, yes we definitely want to wait until it's more mature but also no we don't want to wait because then we might wait forever. So let's do our best to get the upgrade prepared and all of us will monitor the upstream situation because you're absolutely not wrong the upstream situation is a little weird.

This makes sense to you?

**Comment by faddat** [comment]
Well look you got a gift in the form of merge conflicts.

Let's try and work through these together

**Comment by tropicaldog** [comment]
@faddat yeah I think these protobuf files will certainly be diverging from the main branch at somepoint, so not really a big deal I guess.

**Comment by faddat** [comment]
Basically we want to always merge from main so that we are working against the latest code from the main branch.

**Pull request closed without merging**
