### PR TITLE
Web UI updates

### PR DESCRIPTION
**Pull request by joe-bowman**
## 1. Summary

Various refactors to remove hardcoded values, add account mapping, and agoric.

## Summary by CodeRabbit

- **New Features**
	- Streamlined environment variable configuration for production and development, focusing on essential variables.
	- Enhanced asset management with the integration of interchain assets.
	- Improved handling of network configurations using a centralized configuration module.

- **Bug Fixes**
	- Updated logic for fetching RPC and REST endpoints, ensuring accurate data retrieval based on the current environment.

- **Refactor**
	- Simplified component structures and prop types across various components to improve maintainability and clarity.
	- Removed unused imports and redundant code for better performance.
	- Refactored asset management logic to dynamically handle token data.
	- Updated rendering logic to utilize a more consistent naming structure for chain properties.

- **Chores**
	- Updated dependencies in `package.json` to the latest versions for better stability and performance.

### CODE REVIEW

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>c8ac672</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1718.app-dev.quicksilver.zone'>https://pr-1718.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/9n66fBREceHmDsYATzvSgUr7NoSG'>https://vercel.com/quicksilver/quicksilver/9n66fBREceHmDsYATzvSgUr7NoSG</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/10992693457)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>f041bf8</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1718.app-dev.quicksilver.zone'>https://pr-1718.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/AWiDHFHT7TTnbdUrS6Hs5LZt2DF9'>https://vercel.com/quicksilver/quicksilver/AWiDHFHT7TTnbdUrS6Hs5LZt2DF9</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/10993022130)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>c79535e</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1718.app-dev.quicksilver.zone'>https://pr-1718.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/CvrX4NjjKRJ4wzsdDEXKVte3VyMZ'>https://vercel.com/quicksilver/quicksilver/CvrX4NjjKRJ4wzsdDEXKVte3VyMZ</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/10993027096)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>1b1ccac</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1718.app-dev.quicksilver.zone'>https://pr-1718.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/vUvohd1gS3oKR9aTQSZGTS2MtAw6'>https://vercel.com/quicksilver/quicksilver/vUvohd1gS3oKR9aTQSZGTS2MtAw6</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/10993033423)

**Review by chalabi2 — DISMISSED** [review]
Deployment lgtm. Solid changes. Also there is a version of the network drop down selector that has a search bar and just looks better overall in one of the branches I was working on before work stopped.

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>2f56c86</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1718.app-dev.quicksilver.zone'>https://pr-1718.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/2SiBDmHSxAC2yRzvENWBX9xAfKzv'>https://vercel.com/quicksilver/quicksilver/2SiBDmHSxAC2yRzvENWBX9xAfKzv</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/11012034180)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>0d3aacd</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1718.app-dev.quicksilver.zone'>https://pr-1718.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/HeVsksNu2N9KCmvUHPWfEtWXpnLU'>https://vercel.com/quicksilver/quicksilver/HeVsksNu2N9KCmvUHPWfEtWXpnLU</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/11038089147)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>1ad7416</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1718.app-dev.quicksilver.zone'>https://pr-1718.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/BE9AU7BgtqD7FyvobNRodRaTu2vY'>https://vercel.com/quicksilver/quicksilver/BE9AU7BgtqD7FyvobNRodRaTu2vY</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/11039948360)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>88c7832</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1718.app-dev.quicksilver.zone'>https://pr-1718.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/Emr7JhSWbhNn5FFsKUYS3CoRNyxt'>https://vercel.com/quicksilver/quicksilver/Emr7JhSWbhNn5FFsKUYS3CoRNyxt</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/11039956953)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>68bb4fe</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1718.app-dev.quicksilver.zone'>https://pr-1718.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/dnFJR1yEwAo9JJ1sWGxBuvM8gQ4K'>https://vercel.com/quicksilver/quicksilver/dnFJR1yEwAo9JJ1sWGxBuvM8gQ4K</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/11039953719)

**Pull request merged**
