### PR TITLE
Ensure safe casting from math.Int to go primitive type.

### PR DESCRIPTION
**Pull request by tnv1**
## 1. Summary
* Prefer using `String()` when logging amount of `Coin`
* Added check sum of delegation maybe out of bound `Int64()`
* Added check rebalance amount is `Int64` when casting from `math.Int` to `Int64`

## Summary by CodeRabbit

- **Bug Fixes**
  - Enhanced error message clarity by including string representations of values in various functions.
  - Fixed an issue where amounts exceeding `Int64` bounds could cause errors by adding checks and improving error handling.
- **Refactor**
  - Updated logging practices to use string representations for better clarity in logs related to withdrawal records and amount calculations.

### CODE REVIEW

**Review by faddat — APPROVED** [review]
If this passes all of the CI checks, let's get it in. Also, can you please review the changes that code rabbit suggested?

They made sense to me so I committed them, but if they don't make sense to you, please request changes on the pr so that it does not auto merge.

**Comment by faddat** [comment]
@tnv1 could you please lint this?

Try like golangci-lint run ./... --fix

Once all of the ci jobs pass, this pull request will automatically merge.

**Comment by tnv1** [comment]
Yes, thanks sir

**Review by faddat — APPROVED** [review]

**Review by joe-bowman — APPROVED** [review]
lgtm

**Comment by joe-bowman** [comment]
In reality, if any of these fail we are fucked, because int64 is used everywhere :)

**Pull request merged**
