### PR TITLE
ensure go version used in Makefile, Dockerfile and proto-gen match go.mod

### PR DESCRIPTION
**Pull request by joe-bowman**
Ensure we use go1.21 everywhere, and not a combination of the two.

### CODE REVIEW

**Review by ThanhNhann — COMMENTED** [review]
Can we update the `go` version in `go.mod` @joe-bowman ?

**Comment by joe-bowman** [comment]
> Can we update the `go` version in `go.mod` @joe-bowman ?

It was already updated there - this PR is to update it elsewhere.

**Comment by odeke-em** [comment]
@joe-bowman might this be quite premature requiring everyone to install and use Go1.21.1 which was just released less than 14 days ago? Or is this change predicated upon some sort of freshly released security fix? It takes a while for people to get Go updates: even I as a core developer still has Go1.20.X

**Comment by joe-bowman** [comment]
closed on keeping go1.20 for now.

**Pull request closed without merging**
