### PR TITLE
add v1.5.5 upgrade handler

### PR DESCRIPTION
**Pull request by joe-bowman**
Add v1.5.5 upgrade handler

-  fix stuck unbondings
- add claims metadata for qsaga and qdydx
- initialise dust thresholds
- migrate one killer queen incentive account

## Summary by CodeRabbit

- **New Features**
  - Introduced enhancements related to killer queen incentives and protocol data additions.
- **Bug Fixes**
  - Improved error handling in specific financial transaction processes.
- **Refactor**
  - Updated and optimized the handling of withdrawal records and dust delegation thresholds.
- **Tests**
  - Added and updated tests to align with the latest upgrades and error handling improvements.

### CODE REVIEW

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>f72b816</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1445.app-dev.quicksilver.zone'>https://pr-1445.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/BaDAsonfrzDd6xHpjgGRUpma4ysv'>https://vercel.com/quicksilver/quicksilver/BaDAsonfrzDd6xHpjgGRUpma4ysv</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8696022478)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>876f9b8</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1445.app-dev.quicksilver.zone'>https://pr-1445.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/BWJikXtN3ic5Hzw5k1gWLMj9fz9i'>https://vercel.com/quicksilver/quicksilver/BWJikXtN3ic5Hzw5k1gWLMj9fz9i</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8696042286)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>c86c207</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1445.app-dev.quicksilver.zone'>https://pr-1445.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/Dosd1uUgKGmNsmAN8hL5SmUAbUQH'>https://vercel.com/quicksilver/quicksilver/Dosd1uUgKGmNsmAN8hL5SmUAbUQH</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8696044092)

**Review by faddat — APPROVED** [review]

**Review by minhngoc274 — APPROVED** [review]

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>75e8f9f</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1445.app-dev.quicksilver.zone'>https://pr-1445.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/7q3Tj2vr87b4MH4s4xeKWj2TWorm'>https://vercel.com/quicksilver/quicksilver/7q3Tj2vr87b4MH4s4xeKWj2TWorm</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8699274709)

**Review by tropicaldog — APPROVED** [review]

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>cce41e5</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1445.app-dev.quicksilver.zone'>https://pr-1445.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/DT8Seb6txSerfP95noj6NjVaTcQ6'>https://vercel.com/quicksilver/quicksilver/DT8Seb6txSerfP95noj6NjVaTcQ6</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8706459332)

**Comment by joe-bowman** [comment]
@minhngoc274 @tropicaldog @faddat - I fixed (only) the tests, which b0rf the previous approvals. Please re-review. Would like to get this out asap.

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>c6f3a6d</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1445.app-dev.quicksilver.zone'>https://pr-1445.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/AEB9yGLZLxYsL4dWf2NYkT3NRPnD'>https://vercel.com/quicksilver/quicksilver/AEB9yGLZLxYsL4dWf2NYkT3NRPnD</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8706649912)

**Review by faddat — APPROVED** [review]

**Comment by faddat** [comment]
lgtm

@minhngoc274 @tropicaldog please also check -- it's an upgrade handler, more checks, is better.  

thank you.

**Pull request merged**
