### PR TITLE
fixes #1340; remove superfluous []byte() casts for strings in append

### LINKED ISSUE #1340: all: remove the need to convert strings->byteslice in append(byteslice, []byte(string)) because Go's spec permits append(byteslice, string...)
## Summary of Bug
Noticed while auditing x/claimsmanager that there is this pattern
` bz := store.Get(append(types.KeySelfConsensusState, []byte(key)...))`
per https://go.dev/ref/spec#Appending_and_copying_slices
Screenshot 2024-03-26 at 2 32 49 AM

We can simply do
` bz := store.Get(append(types.KeySelfConsensusState, key...))`

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

### PR DESCRIPTION
**Pull request by joe-bowman**
## 1. Summary
Fixes #1340 

change instances of `append(slice, []byte(string)...)` to `append(slice, string...)` as these are equivalent.

## Summary by CodeRabbit

- **New Features**
	- Enhanced formatting in airdrop documentation for better readability.
- **Refactor**
	- Optimized string and byte slice handling across various modules, improving code efficiency and readability.
	- Simplified key generation and data handling in claims manager and interchain staking modules.
- **Bug Fixes**
	- Corrected data handling inconsistencies in participation rewards tests for more accurate testing outcomes.
- **Documentation**
	- Updated airdrop and claims manager README files to correct formatting inconsistencies.

### CODE REVIEW

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>58eaf44</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1360.app-dev.quicksilver.zone'>https://pr-1360.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/5ii5gc9kgzgtpHPg65Nf5undvxkE'>https://vercel.com/quicksilver/quicksilver/5ii5gc9kgzgtpHPg65Nf5undvxkE</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8455958232)

**Review by tropicaldog — APPROVED** [review]
LGTM

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>cd65a17</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1360.app-dev.quicksilver.zone'>https://pr-1360.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/G9brhK68ThWnBggaZYzMVDXM15J1'>https://vercel.com/quicksilver/quicksilver/G9brhK68ThWnBggaZYzMVDXM15J1</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8462087587)

**Comment by joe-bowman** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>a152a40</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://pr-1360.app-dev.quicksilver.zone'>https://pr-1360.app-dev.quicksilver.zone</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/quicksilver/quicksilver/H4v4pEy3z3BbuqcKB73TLwHMMG3T'>https://vercel.com/quicksilver/quicksilver/H4v4pEy3z3BbuqcKB73TLwHMMG3T</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/quicksilver-zone/quicksilver/actions/runs/8462094668)

**Pull request merged**
