### PR TITLE
fix: intermittent test failures

### PR DESCRIPTION
**Pull request by faddat**
## 1. Summary

This PR fixes intermittent test failures on quicksilver, which are platform dependent.

## 2.Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 5. Checklist

- [ ] Does the Readme need to be updated?

## Summary by CodeRabbit

- **Chores**
	- Updated Go version to "1.22" across various workflow files for consistency and compatibility.
	- Streamlined build, test, and simulation processes with updated configurations and simplified event triggers.
	- Refactored workflows to streamline the build and test processes, including simplifying event triggers and adjusting setup for Go versions and operating systems.

### CODE REVIEW

**Comment by faddat** [comment]
there was a space after the .md in the architecture docs.  No, not joking.

**Comment by faddat** [comment]
also windows isn't a real os anyhow

**Comment by faddat** [comment]
@coderabbitai - windows isn't a real os, yeah?

**Comment by joe-bowman** [comment]
The failures are not platform dependent. If one fails the others will auto bail rather than carry on.

The most common issue appears to be Dependabot not having access to the code coverage secret. I posted a fix for this earlier.

Will use go1.22 post 1.5.0 release. It is too immature to use in prod without extensive running on testnet

**Comment by faddat** [comment]
K I'll shelve this for now

**Pull request closed without merging**
