### PR TITLE
update react

### PR DESCRIPTION
**Pull request by faddat**
## 1. Summary
Updates to the latest react.

Should be merged after #913

## 2.Type of change

* version bump

## 5. Checklist

- [ ] Does the Readme need to be updated?

### CODE REVIEW

**Review by chalabi2 — APPROVED** [review]

**Comment by faddat** [comment]
@chalabi2 can you try this on your local machine?  For me, it works fine locally....

**Comment by chalabi2** [comment]
@faddat looks like it works fine

**Comment by chalabi2** [comment]
@faddat this introduces breaking changes

**Comment by faddat** [comment]
@chalabi2 the PR is me trying to fix them & learn what breaks :).  Feel free to ignore drafts :)

**Pull request closed without merging**
